"""Unit tests for email_client.py.

All network I/O is mocked; no real SMTP connection is made.
"""
import os
import smtplib
import unittest
from unittest.mock import MagicMock, patch

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_client(sender="sender@gmail.com", recipient="rcpt@gmail.com", pw="test-pw"):
    from email_client import EmailClient

    return EmailClient(sender=sender, recipient=recipient, app_password=pw)


# ---------------------------------------------------------------------------
# Tests: _markdown_to_html
# ---------------------------------------------------------------------------


class TestMarkdownToHtml(unittest.TestCase):
    def setUp(self):
        self.client = _make_client()

    def test_returns_html_doctype(self):
        html = self.client._markdown_to_html("# Hello")
        self.assertIn("<!DOCTYPE html>", html)

    def test_contains_h1_heading(self):
        html = self.client._markdown_to_html("# My Report")
        self.assertIn("<h1>", html)
        self.assertIn("My Report", html)

    def test_contains_h2_heading(self):
        html = self.client._markdown_to_html("## Section")
        self.assertIn("<h2>", html)

    def test_table_is_rendered(self):
        md = "| A | B |\n|---|---|\n| 1 | 2 |"
        html = self.client._markdown_to_html(md)
        self.assertIn("<table>", html)
        self.assertIn("<th>", html)
        self.assertIn("<td>", html)

    def test_code_block_rendered(self):
        md = "```\nprint('hello')\n```"
        html = self.client._markdown_to_html(md)
        self.assertIn("<code>", html)

    def test_contains_wrapper_div(self):
        html = self.client._markdown_to_html("text")
        self.assertIn('class="wrapper"', html)

    def test_contains_header_div(self):
        html = self.client._markdown_to_html("text")
        self.assertIn('class="header"', html)

    def test_contains_content_div(self):
        html = self.client._markdown_to_html("text")
        self.assertIn('class="content"', html)

    def test_contains_footer_div(self):
        html = self.client._markdown_to_html("text")
        self.assertIn('class="footer"', html)

    def test_footer_contains_generated_by(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("Generated by AIFitnessSummary", html)

    def test_contains_dark_mode_media_query(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("prefers-color-scheme: dark", html)

    def test_contains_mobile_media_query(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("max-width: 480px", html)

    def test_h2_colour_in_css(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("#2c5f8a", html)

    def test_header_background_colour_in_css(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("#1a1a2e", html)

    def test_table_header_background_in_css(self):
        html = self.client._markdown_to_html("text")
        # Table headers use the same brand colour
        self.assertIn("background-color: #2c5f8a", html)

    def test_code_background_in_css(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("#f4f4f4", html)

    def test_dark_mode_background_in_css(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("#1e1e1e", html)

    def test_alternating_row_shading_in_css(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("#f9f9f9", html)

    def test_max_width_in_css(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("max-width: 680px", html)

    def test_body_font_size_in_css(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("font-size: 16px", html)

    def test_line_height_in_css(self):
        html = self.client._markdown_to_html("text")
        self.assertIn("line-height: 1.6", html)


# ---------------------------------------------------------------------------
# Tests: subject line formatting
# ---------------------------------------------------------------------------


class TestSubjectLine(unittest.TestCase):
    def setUp(self):
        self.client = _make_client()

    def test_weekly_subject_format(self):
        subject = self.client._build_subject("weekly", "2026-03-05")
        self.assertIn("Weekly Fitness Digest", subject)
        self.assertIn("March", subject)
        self.assertIn("2026", subject)
        self.assertIn("\u2014", subject)  # em dash

    def test_block_checkin_subject_format(self):
        subject = self.client._build_subject("block_checkin", "2026-03-31")
        self.assertIn("Block Check-In", subject)
        self.assertIn("March", subject)
        self.assertIn("2026", subject)

    def test_end_of_programme_subject_format(self):
        subject = self.client._build_subject("end_of_programme", "2026-06-30")
        self.assertIn("End of Programme Review", subject)
        self.assertIn("June", subject)

    def test_weekly_subject_does_not_contain_only_year(self):
        subject = self.client._build_subject("weekly", "2026-01-01")
        self.assertIn("January", subject)

    def test_block_checkin_capitalised(self):
        subject = self.client._build_subject("block_checkin", "2026-06-30")
        self.assertTrue(subject.startswith("Block"))

    def test_weekly_capitalised(self):
        subject = self.client._build_subject("weekly", "2026-06-30")
        self.assertTrue(subject.startswith("Weekly"))


# ---------------------------------------------------------------------------
# Tests: send_report (mocked SMTP)
# ---------------------------------------------------------------------------


class TestSendReport(unittest.TestCase):
    def _smtp_ctx(self):
        """Return a context-manager mock that mimics SMTP_SSL usage."""
        mock_server = MagicMock()
        mock_cm = MagicMock()
        mock_cm.__enter__ = MagicMock(return_value=mock_server)
        mock_cm.__exit__ = MagicMock(return_value=False)
        return mock_cm, mock_server

    @patch("email_client.smtplib.SMTP_SSL")
    def test_smtp_ssl_called_with_correct_host_port(self, mock_smtp_ssl):
        mock_cm, mock_server = self._smtp_ctx()
        mock_smtp_ssl.return_value = mock_cm

        client = _make_client()
        client.send_report("weekly", "2026-03-05", "# Report")

        mock_smtp_ssl.assert_called_once()
        call_args = mock_smtp_ssl.call_args
        # First two positional-or-keyword args: host, port
        args, kwargs = call_args
        host = args[0] if args else kwargs.get("host")
        port = args[1] if len(args) > 1 else kwargs.get("port")
        self.assertEqual(host, "smtp.gmail.com")
        self.assertEqual(port, 465)

    @patch("email_client.smtplib.SMTP_SSL")
    def test_login_called_with_credentials(self, mock_smtp_ssl):
        mock_cm, mock_server = self._smtp_ctx()
        mock_smtp_ssl.return_value = mock_cm

        client = _make_client(sender="me@gmail.com", pw="secret-pw")
        client.send_report("weekly", "2026-03-05", "# Report")

        mock_server.login.assert_called_once_with("me@gmail.com", "secret-pw")

    @patch("email_client.smtplib.SMTP_SSL")
    def test_sendmail_called(self, mock_smtp_ssl):
        mock_cm, mock_server = self._smtp_ctx()
        mock_smtp_ssl.return_value = mock_cm

        client = _make_client(sender="me@gmail.com", recipient="them@gmail.com")
        result = client.send_report("weekly", "2026-03-05", "# Report")

        mock_server.sendmail.assert_called_once()
        self.assertTrue(result)

    @patch("email_client.smtplib.SMTP_SSL")
    def test_send_report_returns_false_on_smtp_error(self, mock_smtp_ssl):
        mock_smtp_ssl.side_effect = smtplib.SMTPException("connection refused")

        client = _make_client()
        result = client.send_report("weekly", "2026-03-05", "# Report")

        self.assertFalse(result)

    @patch("email_client.smtplib.SMTP_SSL")
    def test_email_contains_both_plain_and_html_parts(self, mock_smtp_ssl):
        """The message sent should be multipart/alternative with plain + HTML."""
        captured = {}

        def fake_sendmail(frm, to, msg_str):
            captured["msg"] = msg_str

        mock_cm, mock_server = self._smtp_ctx()
        mock_server.sendmail.side_effect = fake_sendmail
        mock_smtp_ssl.return_value = mock_cm

        client = _make_client()
        client.send_report("monthly", "2026-03-31", "# Hello\n\nWorld")

        self.assertIn("msg", captured)
        msg_str = captured["msg"]
        self.assertIn("text/plain", msg_str)
        self.assertIn("text/html", msg_str)

    @patch("email_client.smtplib.SMTP_SSL")
    def test_subject_in_sent_message(self, mock_smtp_ssl):
        """Subject header should reference 'Weekly Fitness Review'.

        The MIME encoder may apply RFC-2047 quoted-printable encoding to the
        Subject header when it contains non-ASCII characters (e.g. em dash),
        so we parse the message back out with email.parser to read the
        decoded header value.
        """
        import email as email_module

        captured = {}

        def fake_sendmail(frm, to, msg_str):
            captured["msg"] = msg_str

        mock_cm, mock_server = self._smtp_ctx()
        mock_server.sendmail.side_effect = fake_sendmail
        mock_smtp_ssl.return_value = mock_cm

        client = _make_client()
        client.send_report("weekly", "2026-03-05", "# Hello")

        raw = captured["msg"]
        parsed = email_module.message_from_string(raw)
        # Decode RFC-2047-encoded header words
        from email.header import decode_header, make_header
        subject = str(make_header(decode_header(parsed["Subject"])))
        self.assertIn("Weekly Fitness Digest", subject)


# ---------------------------------------------------------------------------
# Tests: get_email_client factory
# ---------------------------------------------------------------------------


class TestGetEmailClient(unittest.TestCase):
    def _clear_env(self, monkeypatch_dict):
        """Remove email env vars from os.environ for the duration of a test."""
        for key in ("EMAIL_SENDER", "EMAIL_RECIPIENT", "GMAIL_APP_PASSWORD"):
            monkeypatch_dict.pop(key, None)

    def test_returns_none_when_no_env_vars(self):
        from email_client import get_email_client

        env_backup = {k: os.environ.pop(k, None) for k in
                      ("EMAIL_SENDER", "EMAIL_RECIPIENT", "GMAIL_APP_PASSWORD")}
        try:
            result = get_email_client()
            self.assertIsNone(result)
        finally:
            for k, v in env_backup.items():
                if v is not None:
                    os.environ[k] = v

    def test_returns_none_when_only_sender_set(self):
        from email_client import get_email_client

        env_backup = {k: os.environ.pop(k, None) for k in
                      ("EMAIL_SENDER", "EMAIL_RECIPIENT", "GMAIL_APP_PASSWORD")}
        try:
            os.environ["EMAIL_SENDER"] = "me@gmail.com"
            result = get_email_client()
            self.assertIsNone(result)
        finally:
            for k, v in env_backup.items():
                if v is not None:
                    os.environ[k] = v
            os.environ.pop("EMAIL_SENDER", None)

    def test_returns_none_when_sender_empty_string(self):
        from email_client import get_email_client

        env_backup = {k: os.environ.pop(k, None) for k in
                      ("EMAIL_SENDER", "EMAIL_RECIPIENT", "GMAIL_APP_PASSWORD")}
        try:
            os.environ["EMAIL_SENDER"] = ""
            os.environ["EMAIL_RECIPIENT"] = "them@gmail.com"
            os.environ["GMAIL_APP_PASSWORD"] = "pw"
            result = get_email_client()
            self.assertIsNone(result)
        finally:
            for k, v in env_backup.items():
                if v is not None:
                    os.environ[k] = v
            for k in ("EMAIL_SENDER", "EMAIL_RECIPIENT", "GMAIL_APP_PASSWORD"):
                os.environ.pop(k, None)

    def test_returns_email_client_when_all_vars_set(self):
        from email_client import EmailClient, get_email_client

        env_backup = {k: os.environ.pop(k, None) for k in
                      ("EMAIL_SENDER", "EMAIL_RECIPIENT", "GMAIL_APP_PASSWORD")}
        try:
            os.environ["EMAIL_SENDER"] = "me@gmail.com"
            os.environ["EMAIL_RECIPIENT"] = "them@gmail.com"
            os.environ["GMAIL_APP_PASSWORD"] = "abcd-efgh-ijkl-mnop"
            result = get_email_client()
            self.assertIsNotNone(result)
            self.assertIsInstance(result, EmailClient)
        finally:
            for k, v in env_backup.items():
                if v is not None:
                    os.environ[k] = v
            for k in ("EMAIL_SENDER", "EMAIL_RECIPIENT", "GMAIL_APP_PASSWORD"):
                os.environ.pop(k, None)

    def test_returns_none_when_password_missing(self):
        from email_client import get_email_client

        env_backup = {k: os.environ.pop(k, None) for k in
                      ("EMAIL_SENDER", "EMAIL_RECIPIENT", "GMAIL_APP_PASSWORD")}
        try:
            os.environ["EMAIL_SENDER"] = "me@gmail.com"
            os.environ["EMAIL_RECIPIENT"] = "them@gmail.com"
            # GMAIL_APP_PASSWORD intentionally not set
            result = get_email_client()
            self.assertIsNone(result)
        finally:
            for k, v in env_backup.items():
                if v is not None:
                    os.environ[k] = v
            for k in ("EMAIL_SENDER", "EMAIL_RECIPIENT"):
                os.environ.pop(k, None)


if __name__ == "__main__":
    unittest.main()
